# Generated by Django 4.2.11 on 2024-03-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ('title',), 'verbose_name': 'Букет', 'verbose_name_plural': 'Букет'},
        ),
        migrations.AlterModelOptions(
            name='bouquetflower',
            options={'ordering': ('bouquet', 'flower'), 'verbose_name': 'Букет с цветами', 'verbose_name_plural': 'Букет с цветами'},
        ),
        migrations.AlterModelOptions(
            name='bouquetreason',
            options={'ordering': ('bouquet', 'reason'), 'verbose_name': 'Букет по поводу', 'verbose_name_plural': 'Букет по поводу'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('username',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'ordering': ('name',), 'verbose_name': 'Курьер', 'verbose_name_plural': 'Курьер'},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ('name',), 'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветок'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('name',), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастер'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('client_id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ('name',), 'verbose_name': 'Повод', 'verbose_name_plural': 'Повод'},
        ),
    ]
