# Generated by Django 4.2.11 on 2024-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_bouquet_options_alter_bouquetflower_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TimeField(blank=True, null=True, verbose_name='Описание букета'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество цветов'),
        ),
    ]
