# Generated by Django 4.2.11 on 2024-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_bouquet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание букета'),
        ),
    ]
