# Generated by Django 4.2.11 on 2024-03-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_bouquet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_price', models.IntegerField(blank=True, null=True, verbose_name='Желаемая цена')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.client')),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.master')),
                ('reason_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.reason')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультация',
                'ordering': ('client_id',),
            },
        ),
    ]
